import type { NextPage } from "next";
import Head from "next/head";
import Projects from "../data/projects.data";
import ProjectCard from "../components/Cards/ProjectCard";
import Image from "next/image";

import SyntaxHighlighter from "react-syntax-highlighter";
import { docco } from "react-syntax-highlighter/dist/esm/styles/hljs";

const codeString = "(num) => num + 1";

const HomeCard = ({
  title,
  text,
  href,
}: {
  title: string;
  text: string;
  href: string;
}) => (
  <a href={href}>
    <div className="w-72 h-32 bg-white bg-opacity-20 backdrop-blur-lg rounded drop-shadow-lg py-6 px-4 cursor-pointer">
      <h2 className="text-blue-400 text-l font-bold hover:underline">
        {title}
      </h2>
      <p>{text}</p>
    </div>
  </a>
);

const Page: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bolls - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen relative bg-red-300">
        <Image
          src="/me.jpeg"
          alt="Ich wenn"
          layout="fill"
          className="absolute z-0 w-screen"
        />
        {/* <HomeCard title="My Blog" text="dings" href="https://blog.bolls.dev" />
        <HomeCard
          title="My Projects"
          text="dings"
          href="https://blog.bolls.dev"
        />
        <HomeCard title="Contact" text="dings" href="https://blog.bolls.dev" />
        <HomeCard title="Resume" text="dings" href="https://blog.bolls.dev" /> */}
        {/* <SyntaxHighlighter language="typescript" style={docco}>
          {codeString}
        </SyntaxHighlighter> */}
      </div>

      <main className="relative z-10">
        <h1 className="text-3xl text-gray-700">Herzlich Willkommen :)</h1>

        <p className="text-xl font-bold text-blue-400">
          Ich bin Linus, ein Weichware-Entwickler mit einer Leidenschaft für
          skalierbaren Code und simples Design.
        </p>
      </main>
    </>
  );
};
export default Page;
