import type { NextPage } from "next";
import Head from "next/head";
import Projects from "../data/projects.data";
import ProjectCard from "../components/ProjectCard";
import Image from "next/image";

const HomeCard = ({
  title,
  text,
  href,
}: {
  title: string;
  text: string;
  href: string;
}) => (
  <a href={href}>
    <div className="w-72 h-32 bg-white bg-opacity-20 backdrop-blur-lg rounded drop-shadow-lg py-6 px-4 cursor-pointer">
      <h2 className="text-blue-400 text-l font-bold hover:underline">
        {title}
      </h2>
      <p>{text}</p>
    </div>
  </a>
);

const Page: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen">
        <Image
          src="/me.jpeg"
          alt="Vercel Logo"
          layout="fill"
          className="absolute z-0"
        />
        <HomeCard title="My Blog" text="dings" href="https://blog.bolls.dev" />
        <HomeCard
          title="My Projects"
          text="dings"
          href="https://blog.bolls.dev"
        />
        <HomeCard title="Contact" text="dings" href="https://blog.bolls.dev" />
        <HomeCard title="Resume" text="dings" href="https://blog.bolls.dev" />
      </div>

      <main className="relative z-10">
        <h1 className="text-3xl text-gray-700">Herzlich Willkommen :)</h1>

        <p className="text-xl font-bold text-blue-400">
          Ich bin Linus, ein Weichware-Entwickler mit einer Leidenschaft für
          skalierbaren Code und simples Design.
        </p>

        <div className="flex flex-row flex-wrap gap-10 mt-40 mb-10 justify-between">
          {Object.entries(Projects).map(([key, project]) => (
            <ProjectCard key={key} project={project} />
          ))}
        </div>

        <div>
          <a href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
        </a>
      </footer>
    </div>
  );
};
export default Page;
